### ISSUE TITLE
Intersection Types missing

### ISSUE THREAD

**Issue by evdama** [rmolinamir/typescript-cheatsheet#1]
Intersection Types are missing. First thing the official docs mention https://www.typescriptlang.org/docs/handbook/advanced-types.html :)

**Comment by rmolinamir** [comment]
Thank you so much! That really means a lot to me, I' very glad you find it useful. That's what I was going for when I did it 😃

**Comment by rmolinamir** [comment]
Hi!

Thanks a lot for bringing this up! I think I might have used intersection types in some of the examples throughout the cheatsheet but never mentioned them. I'll definitely add the intersection types this weekend, thank you @evdama.

Best of luck!

**Comment by evdama** [comment]
Excellent! I honestly think your cheatsheet is the most practical and terse one out there... very useful imo!

**Comment by rmolinamir** [comment]
@evdama 
I've sent you a collaborator invite here in case you want to review the PR's regarding intersection types or submit any new PR's in the future. I will be merging the intersection types PR anyways by tomorrow evening in either case, but feel free to comment on anything you might come across! I'll be adding notes regarding React hooks this weekend.

Finally, I'll close this issue *after* the branch is merged.

In any case, best of luck!

**Comment by evdama** [comment]
thanks much!
I'll make improvements as I see fit... haven't read through it entirely yet :)

**Comment by rmolinamir** [comment]
Great! I requested a review for the PR that includes the intersection types!

Also, no worries! No need to do a throughout check, it's just in case you come across something that catches your eye.

**Comment by evdama** [comment]
made comments on the PR, therefore closing this one
