### ISSUE TITLE
React Hooks / Typescript Types

### ISSUE THREAD

**Issue by evdama** [rmolinamir/typescript-cheatsheet#2]
Typings for react hooks are also very useful so I suggest adding a section on how to use typescript types on react hooks e.g. https://fettblog.eu/typescript-react/hooks/ and https://levelup.gitconnected.com/usetypescript-a-complete-guide-to-react-hooks-and-typescript-db1858d1fb9c

**Comment by rmolinamir** [comment]
That is a very nice idea! I've already done a few projects with heavy usage of hooks and there are quite a few things worth noting. Will also work on these additions this weekend, thanks again @evdama!

**Comment by rmolinamir** [comment]
Hey @evdama! 

I've finally finished adding a section for each of the react hooks and for custom hooks. If you're still interested in this, feel free to share your thoughts :)

Thanks!

**Comment by evdama** [comment]
I went all in on svelte/sapper and UIkit... totally dropped react and its
entire ecosystem :)
