### ISSUE TITLE
Reference to reduxjs is a broken link

### ISSUE THREAD

**Issue by kberg** [rmolinamir/typescript-cheatsheet#25]
In https://rmolinamir.github.io/typescript-cheatsheet/#intersection there's a reference to https://github.com/reduxjs/redux/blob/master/src/compose.js### which gives a 404.

**Comment by rmolinamir** [comment]
Thanks @kberg, fixed in [9e932d9](https://github.com/rmolinamir/typescript-cheatsheet/commit/9e932d9a5650fa939cd0d05ce82ba4aa60c4ac6c).
