### ISSUE TITLE
Strict null checks

### ISSUE THREAD

**Issue by Svish** [rmolinamir/typescript-cheatsheet#26]
I might have misunderstood, but I think the issue mentioned under https://rmolinamir.github.io/typescript-cheatsheet/#difference-between-optional-properties-and-undefined-or-null-properties-of-any-type-variable-and-type--undefined--null would not be an issue if strict null checks were enabled in tsconfig? Which it _really_ should be, so maybe would be good to mention that?

I think `age?: number` , with strict null checks, would get the type `number | undefined`.

**Comment by rmolinamir** [comment]
Hey @Svish! Sorry for the late reply.

I definitely agree with you there, I can't even remember why the heck the code was even being compiled, maybe some issue in an old TypeScript version or perhaps an undesired `tsconfig` file was being used? I tried compiling it in the playground and it's throwing errors as should be expected. I'll tinker that section over the weekend, will leave this issue open in the meantime!

**Comment by rmolinamir** [comment]
Fixed in [9f4c910](https://github.com/rmolinamir/typescript-cheatsheet/commit/9f4c910bd994bd92cad973e89012fa12720c32b6).
