### ISSUE TITLE
[LOGICAL ERROR] In computer science, imperative programming focuses on what the program should accomplish without specifying how the program should achieve the result.

### ISSUE THREAD

**Issue by MaxmaxmaximusAWS** [rmolinamir/typescript-cheatsheet#27]
https://rmolinamir.github.io/typescript-cheatsheet/#useimperativehandle

> In computer science, imperative programming focuses on what the program should accomplish without specifying how the program should achieve the result.

In fact, the opposite is true =)
---
https://en.wikipedia.org/wiki/Imperative_programming

> In computer science, imperative programming is a programming paradigm that uses statements that change a program's state. In much the same way that the imperative mood in natural languages expresses commands, an imperative program consists of commands for the computer to perform. Imperative programming focuses on describing how a program operates.

> The term is often used in contrast to declarative programming, which focuses on what the program should accomplish without specifying how the program should achieve the result.

**Comment by rmolinamir** [comment]
@MaxmaxmaximusAWS Thanks!

I'm an idiot 🤦‍♂️ 😄

**Comment by rmolinamir** [comment]
Fixed in [9f4c910](https://github.com/rmolinamir/typescript-cheatsheet/commit/9f4c910bd994bd92cad973e89012fa12720c32b6).

**Comment by MaxmaxmaximusAWS** [comment]
@rmolinamir your like politician 😄😄😄

![image](https://user-images.githubusercontent.com/69426460/95647163-f898b000-0ad5-11eb-82a2-6d0b802a80f0.png)
