### ISSUE TITLE
dont' require a PR for little things such as fixing typos

### ISSUE THREAD

**Issue by evdama** [rmolinamir/typescript-cheatsheet#7]
as it creates way to much overhead

I just fixed a typo, have a local commit and can't push anymore; I guess you mentioned making PRs mandatory for all and everything. Let's allow little things like fixing typos though, otherwise tiny things take up to much time...

**Comment by rmolinamir** [comment]
Alrighty! I just changed it back. Don't think it's necessary to make PR's mandatory for now but at least the rule will exist in case we want to apply it in the future.

**Comment by rmolinamir** [comment]
Will close this one, if for some reason it didn't work, just reopen it 👍

**Comment by evdama** [comment]
Great! A PR for bigger, more significant things makes sense, even just to discuss stuff. I'll adhere to that.
